// PROPOSED — not deployed. Replaces the original verify-staff-pin function
// (source unseen by this audit, see AUDIT.md §11.2) with an implementation
// whose PIN handling, hashing, and rate limiting are fully readable here.
//
// Request:  POST { store_id: uuid, pin: string (4 digits), client_ref: string }
// Response: 200 { ok: true, access_token, expires_at, staff: {id,name,role,store_id} }
//        or 200 { ok: false, error: string }   -- see note on status codes below
//
// Runs with the service_role key so it can read staff.pin_hash, which is
// otherwise unreachable from any client role (see 0002_staff_and_audit.sql
// and 0005_rls_policies.sql) -- this function is deliberately the *only*
// code path that can see that column.
import { createClient } from 'npm:@supabase/supabase-js@2';
import { verifyPin } from '../_shared/hash.ts';
import { signSessionToken } from '../_shared/jwt.ts';
import { corsHeaders } from '../_shared/cors.ts';

const SUPABASE_URL = Deno.env.get('SUPABASE_URL')!;
const SERVICE_ROLE_KEY = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
// Named TT_JWT_SECRET (not SUPABASE_JWT_SECRET) because `supabase secrets
// set` rejects any name starting with SUPABASE_ -- that prefix is reserved
// for the platform's own auto-injected values. Must be set manually to the
// project's real JWT secret -- see AUTH_MODEL.md.
const JWT_SECRET = Deno.env.get('TT_JWT_SECRET')!;

// Rate limiting thresholds. Tuned for a shared shop device where a handful
// of genuine mistyped PINs per shift is normal, but 4-digit brute forcing
// (10,000 combinations) must be made impractically slow.
const MAX_ATTEMPTS_PER_WINDOW = 8;
const WINDOW_MINUTES = 15;
const LOCKOUT_MINUTES = 15;

function json(body: unknown, status: number, origin: string | null) {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...corsHeaders(origin), 'Content-Type': 'application/json' },
  });
}

Deno.serve(async (req) => {
  const origin = req.headers.get('origin');
  if (req.method === 'OPTIONS') return new Response('ok', { headers: corsHeaders(origin) });
  if (req.method !== 'POST') return json({ ok: false, error: 'Method not allowed' }, 405, origin);

  let body: { store_id?: string; pin?: string; client_ref?: string };
  try {
    body = await req.json();
  } catch {
    return json({ ok: false, error: 'Invalid request body' }, 400, origin);
  }

  const { store_id, pin, client_ref } = body;
  if (!store_id || !pin || !/^\d{4}$/.test(pin) || !client_ref) {
    return json({ ok: false, error: 'store_id, a 4-digit pin, and client_ref are required' }, 400, origin);
  }

  // Best-effort IP signal -- this, not client_ref, is the real backstop
  // against brute forcing, because client_ref is generated by the caller
  // and trivially spoofable (an attacker can mint a fresh one per request).
  // client_ref is still recorded for UX/observability ("this device is
  // temporarily locked") but must never be the *only* rate-limit key.
  const ipHint = req.headers.get('x-forwarded-for')?.split(',')[0]?.trim() ?? 'unknown';

  const supabase = createClient(SUPABASE_URL, SERVICE_ROLE_KEY);

  const windowStart = new Date(Date.now() - WINDOW_MINUTES * 60_000).toISOString();
  const { count: recentFailures, error: countError } = await supabase
    .from('pin_login_attempts')
    .select('*', { count: 'exact', head: true })
    .eq('store_id', store_id)
    .eq('ip_hint', ipHint)
    .eq('success', false)
    .gte('attempted_at', windowStart);

  if (countError) {
    console.error('pin_login_attempts count failed', countError);
    return json({ ok: false, error: 'Could not check PIN right now — try again shortly' }, 500, origin);
  }
  if ((recentFailures ?? 0) >= MAX_ATTEMPTS_PER_WINDOW) {
    return json(
      { ok: false, error: `Too many attempts. Try again in a few minutes.` },
      429,
      origin,
    );
  }

  const { data: candidates, error: staffError } = await supabase
    .from('staff')
    .select('id, name, role, pin_hash, locked_until')
    .eq('home_store_id', store_id)
    .eq('active', true)
    .not('pin_hash', 'is', null);

  if (staffError) {
    console.error('staff lookup failed', staffError);
    return json({ ok: false, error: 'Could not check PIN right now — try again shortly' }, 500, origin);
  }

  let matched: { id: string; name: string; role: string; locked_until: string | null } | null = null;
  for (const candidate of candidates ?? []) {
    // Every candidate is checked (not short-circuited on first match) so
    // response timing doesn't leak how many staff share a store — cheap
    // enough at realistic staff-list sizes (tens of people, not thousands).
    const isMatch = await verifyPin(pin, candidate.pin_hash as string);
    if (isMatch) matched = candidate;
  }

  await supabase.from('pin_login_attempts').insert({
    store_id,
    client_ref,
    ip_hint: ipHint,
    staff_id: matched?.id ?? null,
    success: !!matched,
  });

  if (!matched) {
    return json({ ok: false, error: 'Incorrect PIN' }, 200, origin);
  }

  if (matched.locked_until && new Date(matched.locked_until) > new Date()) {
    return json({ ok: false, error: 'This account is temporarily locked. Ask a manager for help.' }, 200, origin);
  }

  await supabase.from('staff').update({ failed_pin_attempts: 0, locked_until: null }).eq('id', matched.id);

  const { token, expiresAt } = await signSessionToken(
    { staff_id: matched.id, store_id, staff_role: matched.role as 'staff' | 'manager', name: matched.name },
    JWT_SECRET,
  );

  await supabase.from('audit_log').insert({
    store_id,
    actor_id: matched.id,
    action: 'staff_signed_in',
    entity_type: 'staff',
    entity_id: matched.id,
  });

  return json(
    {
      ok: true,
      access_token: token,
      expires_at: expiresAt,
      staff: { id: matched.id, name: matched.name, role: matched.role, store_id },
    },
    200,
    origin,
  );
});

// ---- Deliberately unresolved for this proposal ------------------------------
// 1. LOCKOUT_MINUTES / the staff.locked_until column are populated by the
//    set-staff-pin function (manager-initiated lock) — this function does
//    not auto-lock a specific staff row from anonymous failed guesses,
//    because a guess that matches no one can't be attributed to a specific
//    staff member. Device/IP-level throttling above is the automated
//    defense; per-staff locking is a manual manager action. Flagging this
//    tradeoff explicitly rather than pretending both are automatic.
// 2. pin_login_attempts grows unboundedly without a cleanup job — see
//    0006_pin_login_attempts.sql's comment.
